const products = [
  { id: "bottega", name: "Bottega Gold Prosecco", brand: "Bottega", category: "Champagne", volume: "75cl · 11%", price: 38500, image: "assets/products/bottega-gold.png", tag: "A proper toast" },
  { id: "hennessy", name: "Hennessy Very Special", brand: "Hennessy", category: "Spirits", volume: "70cl · 40%", price: 67000, image: "assets/products/hennessy-vs.jpg", tag: "Host’s choice" },
  { id: "jack", name: "Jack Daniel’s Old No. 7", brand: "Jack Daniel’s", category: "Spirits", volume: "70cl · 40%", price: 42000, image: "assets/products/jack-daniels.png", tag: "Tennessee whiskey" },
  { id: "heineken", name: "Heineken Original Lager", brand: "Heineken", category: "Beer", volume: "33cl · 5%", price: 1900, image: "assets/products/heineken.jpg", tag: "Serve cold" },
  { id: "bottega-rose", name: "Bottega Gold Rosé", brand: "Bottega", category: "Wine", volume: "75cl · 11.5%", price: 39500, image: "assets/products/bottega-gold.png", tag: "For dinner" },
  { id: "hennessy-cocktail", name: "Hennessy & Ginger Set", brand: "Hennessy", category: "Spirits", volume: "70cl · 40%", price: 69000, image: "assets/products/hennessy-vs.jpg", tag: "Easy serve" },
  { id: "jack-gift", name: "Jack Daniel’s Gift Bottle", brand: "Jack Daniel’s", category: "Spirits", volume: "70cl · 40%", price: 45000, image: "assets/products/jack-daniels.png", tag: "Bring a bottle" },
  { id: "heineken-pack", name: "Heineken Lager Pack", brand: "Heineken", category: "Beer", volume: "6 × 33cl · 5%", price: 10500, image: "assets/products/heineken.jpg", tag: "Weekend ready" },
];
const state = { cart: JSON.parse(localStorage.getItem("yodla-cart") || "[]"), category: "All", location: localStorage.getItem("yodla-location") || "" };
const money = (amount) => `₦${amount.toLocaleString("en-NG")}`;
const productGrid = document.getElementById("product-grid");
const getProduct = (id) => products.find((product) => product.id === id);
function saveCart() { localStorage.setItem("yodla-cart", JSON.stringify(state.cart)); }
function renderProducts() { const shown = products.filter((product) => state.category === "All" || product.category === state.category); productGrid.innerHTML = shown.map((product) => `<article class="product-card" data-od-id="product-${product.id}"><div class="product-card__image"><span class="product-card__tag">${product.tag}</span><img src="${product.image}" alt="${product.name}"></div><h3>${product.name}</h3><p>${product.brand} · ${product.volume}</p><div class="product-card__bottom"><strong>${money(product.price)}</strong><button class="add-button" data-add="${product.id}" aria-label="Add ${product.name} to bag">+</button></div></article>`).join(""); document.querySelectorAll(".filter-chip").forEach((chip) => chip.classList.toggle("is-active", chip.dataset.category === state.category)); }
function renderCart() { const count = state.cart.reduce((total, item) => total + item.quantity, 0); const total = state.cart.reduce((sum, item) => sum + getProduct(item.id).price * item.quantity, 0); document.getElementById("cart-count").textContent = count; document.getElementById("cart-total").textContent = money(total); const container = document.getElementById("cart-items"); container.innerHTML = state.cart.length ? state.cart.map((item) => { const product = getProduct(item.id); return `<div class="cart-row"><img src="${product.image}" alt=""><div class="cart-row__details"><h3>${product.name}</h3><p>${money(product.price)}</p><div class="quantity-control"><button data-quantity="${product.id}" data-change="-1" aria-label="Reduce quantity">−</button><span>${item.quantity}</span><button data-quantity="${product.id}" data-change="1" aria-label="Increase quantity">+</button><button class="remove-button" data-remove="${product.id}">Remove</button></div></div></div>`; }).join("") : `<p class="empty-state">Your bag is waiting for something good.</p>`; saveCart(); }
function toast(message) { const el = document.getElementById("toast"); el.textContent = message; el.classList.add("is-visible"); window.setTimeout(() => el.classList.remove("is-visible"), 2200); }
function addToCart(id) { const line = state.cart.find((item) => item.id === id); if (line) line.quantity += 1; else state.cart.push({ id, quantity: 1 }); renderCart(); toast(`${getProduct(id).name} added to your bag.`); }
function adjustCart(id, change) { const line = state.cart.find((item) => item.id === id); if (!line) return; line.quantity += change; if (line.quantity < 1) state.cart = state.cart.filter((item) => item.id !== id); renderCart(); }
function openDrawer(id) { document.getElementById("backdrop").hidden = false; document.querySelectorAll(".drawer").forEach((drawer) => drawer.classList.remove("is-open")); const drawer = document.getElementById(id); drawer.classList.add("is-open"); drawer.setAttribute("aria-hidden", "false"); document.body.style.overflow = "hidden"; }
function closeDrawers() { document.querySelectorAll(".drawer").forEach((drawer) => { drawer.classList.remove("is-open"); drawer.setAttribute("aria-hidden", "true"); }); document.getElementById("backdrop").hidden = true; document.body.style.overflow = ""; }
function setCategory(category) { state.category = category; renderProducts(); closeDrawers(); document.getElementById("filter-count").textContent = category === "All" ? "" : "· 1"; }
function renderSearch(term) { const result = products.filter((p) => `${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(term.toLowerCase())); document.getElementById("search-results").innerHTML = term ? (result.length ? result.map((p) => `<button class="search-row" data-add="${p.id}"><img src="${p.image}" alt=""><span><h3>${p.name}</h3><p>${p.volume} · ${money(p.price)}</p></span></button>`).join("") : `<p class="empty-state">No bottles match that search yet.</p>`) : `<p class="empty-state">Try champagne, whisky, beer or a brand.</p>`; }
document.addEventListener("click", (event) => { const add = event.target.closest("[data-add]"); const quantity = event.target.closest("[data-quantity]"); const remove = event.target.closest("[data-remove]"); const category = event.target.closest("[data-category]"); const occasion = event.target.closest("[data-filter]"); if (add) addToCart(add.dataset.add); if (quantity) adjustCart(quantity.dataset.quantity, Number(quantity.dataset.change)); if (remove) { state.cart = state.cart.filter((item) => item.id !== remove.dataset.remove); renderCart(); } if (category) setCategory(category.dataset.category); if (occasion) setCategory(occasion.dataset.filter); });
document.getElementById("cart-trigger").addEventListener("click", () => openDrawer("cart-drawer"));
document.getElementById("search-trigger").addEventListener("click", () => { openDrawer("search-drawer"); document.getElementById("search-input").focus(); });
document.getElementById("location-trigger").addEventListener("click", () => openDrawer("location-drawer"));
document.getElementById("filter-trigger").addEventListener("click", () => openDrawer("filter-drawer"));
document.querySelectorAll("[data-close-drawer]").forEach((button) => button.addEventListener("click", closeDrawers));
document.getElementById("backdrop").addEventListener("click", closeDrawers);
document.getElementById("search-input").addEventListener("input", (event) => renderSearch(event.target.value));
document.getElementById("save-location").addEventListener("click", () => { const location = document.getElementById("location-select").value; if (!location) return toast("Choose a state or city first."); state.location = location; localStorage.setItem("yodla-location", location); document.querySelector(".announcement").firstChild.textContent = `Delivery location: ${location}. `; closeDrawers(); toast(`Location set to ${location}.`); });
document.getElementById("checkout-trigger").addEventListener("click", () => { if (!state.cart.length) return toast("Add a bottle before checkout."); closeDrawers(); document.getElementById("checkout-modal").hidden = false; });
document.querySelectorAll("[data-close-modal]").forEach((button) => button.addEventListener("click", () => { document.getElementById("checkout-modal").hidden = true; }));
document.querySelectorAll(".article-trigger").forEach((button) => button.addEventListener("click", () => toast("The Yodla Journal opens with the full editorial collection.")));
document.addEventListener("keydown", (event) => { if (event.key === "Escape") { closeDrawers(); document.getElementById("checkout-modal").hidden = true; } });
if (state.location) document.querySelector(".announcement").firstChild.textContent = `Delivery location: ${state.location}. `;
renderProducts(); renderCart(); renderSearch("");
