export const DEFAULT_SITE = {
  announcement: "Thoughtfully selected. Responsibly delivered. 18+ only.",
  navigation: [
    { label: "Shop all", href: "shop.html" },
    { label: "Hosting", href: "shop.html?occasion=Hosting" },
    { label: "Extras", href: "shop.html?category=Extras" },
    { label: "Journal", href: "journal.html" },
  ],
  footerTagline: "Good bottles. Good company.",
  footerDescription: "A contemporary drinks store built around Nigerian tables, nights and celebrations.",
  supportEmail: "hello@yodla.ng",
  supportPhone: "",
  socialLinks: [],
  responsibleDrinking: "Drink responsibly · 18+",
  prototypeLabel: "Prototype storefront",
  help: {
    eyebrow: "Help, without the runaround",
    title: "What do you need to know?",
    description: "Clear answers about delivery, returns and ordering.",
    sections: [
      { key: "delivery", title: "Delivery", question: "Where does Yodla deliver?", answer: "This prototype supports Lagos, Abuja, Ibadan and Port Harcourt, with availability shown per product." },
      { key: "returns", title: "Returns", question: "Can I return a bottle?", answer: "Unopened, undamaged products can be returned. Chilled items and opened bottles are excluded." },
      { key: "contact", title: "Contact", question: "How do I reach the team?", answer: "Email hello@yodla.ng for Yodla support." },
    ],
  },
};

export const DEFAULT_HOME = {
  hero: {
    eyebrow: "For tonight, and what it becomes",
    title: "Bring the\ngood part.",
    description: "Drinks worth opening, selected for Nigerian tables, soft landings and loud celebrations.",
    primaryLabel: "Browse the shelves",
    primaryHref: "shop.html",
    imageProductId: "celebration-duo",
    imageAlt: "A Yodla celebration gift set",
    caption: "A bottle for the arrival",
    captionStrong: "The Celebration Duo",
    stamp: "Selected for the moment",
  },
  heroSlides: [
    {
      id: "celebration",
      image: "assets/products/originals/celebration-set.png",
      responsiveBase: "hero-celebration",
      imageAlt: "A Yodla celebration gift set with sparkling wine and a dark spirit",
      caption: "A bottle for the arrival",
      captionStrong: "The Celebration Duo",
      stamp: "Selected for the moment",
      occasion: "Gift",
      href: "shop.html?occasion=Gift",
    },
    {
      id: "dinner",
      image: "assets/products/originals/hero-dinner.png",
      responsiveBase: "hero-dinner",
      imageAlt: "An unbranded red wine bottle and two glasses arranged for dinner",
      caption: "For the table that lingers",
      captionStrong: "Dinner, poured slowly",
      stamp: "Stay for another glass",
      occasion: "Dinner",
      href: "shop.html?occasion=Dinner",
    },
    {
      id: "hosting",
      image: "assets/products/originals/hero-hosting.png",
      responsiveBase: "hero-hosting",
      imageAlt: "An unbranded botanical bottle with two lime highballs",
      caption: "For a fuller room",
      captionStrong: "Hosting, made easy",
      stamp: "Ready for good company",
      occasion: "Hosting",
      href: "shop.html?occasion=Hosting",
    },
    {
      id: "zero",
      image: "assets/products/originals/hero-zero.png",
      responsiveBase: "hero-zero",
      imageAlt: "An unbranded alcohol-free botanical bottle with citrus spritzes",
      caption: "A bright pour for everyone",
      captionStrong: "Zero, with character",
      stamp: "Nothing missing",
      occasion: "Alcohol-free",
      href: "shop.html?category=Mixers%20%26%20Soft%20Drinks",
    },
  ],
  occasions: [
    { key: "Dinner", eyebrow: "A slower table", title: "Dinner that runs late", action: "Find the bottle" },
    { key: "Hosting", eyebrow: "A fuller fridge", title: "Everyone is coming", action: "Stock up" },
    { key: "Gift", eyebrow: "Arrive properly", title: "Something they will open", action: "Choose a gift" },
  ],
  featuredProductIds: ["bottega-gold", "hennessy-vs", "midnight-red", "palm-botanical-gin"],
  manifesto: {
    eyebrow: "The Yodla way",
    title: "Less shelf noise.\nMore good nights.",
    description: "We organise drinks around how people actually gather—not an endless aisle of tiny decisions.",
    steps: [
      { title: "Choose the moment", body: "Dinner, hosting, gifting, or the weekend." },
      { title: "Set your city", body: "See what is ready where you are." },
      { title: "Open something good", body: "We make the final stretch feel effortless." },
    ],
  },
  journalPromotionId: "highball-for-a-full-house",
};

export const DEFAULT_CONTENT_META = {
  source: "static",
  stale: false,
  message: "Showing the bundled Yodla catalogue.",
};
